os: linux
dist: xenial
language: java
jdk:
  - openjdk8
  - openjdk11
before_install:
  - rm ~/.m2/settings.xml || true
  - ulimit -c unlimited -S
install: skip
script:
  - ./mvnw -V -B -ff verify
after_success:
  - bash ci/after_success.sh
cache:
  directories:
    - "$HOME/.m2"
deploy:
  - provider: script
    script: bash ci/deploy-snapshot.sh
    on:
      repo: dropwizard/dropwizard-web
      tags: false
      branch: master
      jdk: openjdk8
      condition: $PUBLISH = true
  - provider: script
    script: bash ci/deploy-release.sh
    on:
      repo: dropwizard/dropwizard-web
      tags: true
      jdk: openjdk8
      condition: $PUBLISH = true
env:
  global:
    - secure: NvFF0MPF4urmQagad8YZ9fLd3VpEoud0FSlVPO4vg/vP5yrXLagk1KpDanijYbMYEjGnIlcfKRAhqqrYvhq2cvySpIWOD3l3oxLJ3/kLTXf0PECXS4B13Qa/YKs0YwaFtyBjX4ezHkyqiWNGzT3mq+NctLqQuUqK96kXY8vnmruhZK63+V4XK9AWvhQzIUEWY7Ymp899NxunTsXi3wEaHDAkD+NS5VliAgI4lsgG2WKAMmqijz4knY9Ow89pla90CvBOrEywVjjgIbWeMRyDymtN1S3g57ToG6Rkl9GygCD2WMoMqniIrJgsZDqUTuTA9aWP4lPBJGHxUPwxTpzQuZYVRKE8ItJWzksNQObpujPN9DC8mHWhuK5Bo/nsnVu8f+9pot77FpJqa2Ks3qkPghXXrI63i9fdJLXk1JSv9AsxuCKBg0zvTrDkAafxO5k9l/9xkUwXq97ohGK4QEbrb/0gTaFPfVprl+/9MTmIgFz9r4B0607q80DDERxTabJaVgKGq348QjY1YS/IrVtie6X9MSJFaWObTnXPPwPnfgMlYFsE1vy3ybgSlGNihKkizMmEv5yg9a583wof/BK0Edoq/Wc7UYS0LPjoICjeIW1OkIPQooTvw/zA2TDuFyoPCaHccvC/NL70BIx4xhN9xDQJNWeFTnqW8Ms/g6avYrQ=
    - secure: wQqMAM+yVPwyzbpeltKut4R+t/jS37nBs+cU3gp+dUdgBDUgDbnwKq9KaF0q2oLcqgbsq8Uvzqr6jy8Zkks9veJMSgOjA4I7HVkDLbcksbhQHfWOzn/qGhmtvpyfCQnAEmDM2Juomrmf360iymHXh3sV0TjAixp2gzbW44dPIrViBw7rL5N5x/wYTmyiUungHYdCTPPqnNNmJszBJT2culgsu9yBIzpP7rDx3qjDh+NdVCSp9n85/WlwR2FYKKoV5toU00sQDMR70JvElrz5vydaOfN139OhhtLou4RoMyhkbfDB2xFreil648Y23ZDGu5q9t5CwJBf+fS3uBKJqdGdl8B3GWllmEQoiHMi5tBYvu8yZyirn5ry30+pTb21HD6BCzUC+amjfEpDjzyvm4ZjeEcntc+EsALzZTkfQSIVnaxNTHnYt6nvJMsjOjSE0YEL4qfElIVn3ggu6cm8waZyoazSESOjZZexZrU5woara5uDd1VIxQdrUEnz2ZqmlKTIGq+/ajHA6VZTJYwZUZ5gawq61ofpR52xkYsOWltL9DLYlS0MaHsekR5+z6c/kzqu3a6P2k/8L5xIQ9LoPugupJw6BS8eMBlI6KoBiUvBaC2RtZELJa1t/4VfTqZdVCAWAp4a5VSZAm7QHlqxfikrrCj4ypWlzDbRiiy89oCQ=
  jobs:
    - DROPWIZARD_MAJOR_VERSION=2 PUBLISH=true
    - DROPWIZARD_MAJOR_VERSION=1
